version: '3.9'

services:
  node_backend:
    image: ${IMAGE}
    command: run
    env_file: .env.backend
    volumes:
      - db:/db
    ports:
      - '17000:17000'
      - '17001:17001'
    labels:
      - 'traefik.enable=true'
      - 'traefik.http.routers.node-backend.entrypoints=websecure'
      - 'traefik.http.routers.node-backend.tls=true'
      - 'traefik.http.routers.node-backend.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.node-backend.rule=Host(`$NODE_BACKEND_HOST`) && PathPrefix(`/api/`)'
      - 'traefik.http.services.node-backend.loadbalancer.server.port=17001'
    restart: unless-stopped

volumes:
  db:
    driver: local

networks:
  default:
    name: bigwig
