version: '3.9'

services:
  node_backend:
    image: ${NODE_BACKEND_IMAGE}
    env_file: .env.backend
    volumes:
      - db:/db
    networks:
      - node_backend_prod
      - traefik
    ports:
      - '17000:17000'
      - '17001:17001'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=traefik'
      - 'traefik.http.routers.node-backend-prod.entrypoints=websecure'
      - 'traefik.http.routers.node-backend-prod.tls=true'
      - 'traefik.http.routers.node-backend-prod.tls.certresolver=letsencrypt'
      - 'traefik.http.routers.node-backend-prod.rule=Host(`$NODE_BACKEND_HOST`) && PathPrefix(`/api/`)'
      - 'traefik.http.services.node-backend-prod.loadbalancer.server.port=17001'
    restart: unless-stopped

volumes:
  db:
    driver: local

networks:
  node_backend_prod:
    name: node_backend_prod
  traefik:
    name: traefik
